services:
  - type: web
    name: vdarpan-directory
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: NODE_VERSION
        value: 18.20.0